server:
  port: 9001
spring:
  application:
    name: hrm-sysmanage
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hrm_sysmanage
      username: root
      password: 123
mybatis-plus:
  mapper-locations: classpath:com/zh/hrm/mapper/*Mapper.xml
  type-aliases-package: com.zh.hrm.domain,cn.itsource.hrm.query