server:
  port: 9002
spring:
  application:
    name: hrm-course
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrm_course
    username: root
    password: 123
mybatis-plus:
  mapper-locations: classpath:com/zh/hrm/mapper/*Mapper.xml
  type-aliases-package: com.zh.hrm.domain,com.zh.hrm.query
